AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ${className}Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java8
#if (${handlerType} == 'simple')
      Handler: ${package}.${className}::handler
#else
      Handler: ${package}.${className}::handleRequest
#end
      Timeout: 60
      CodeUri: ./target/lambda.jar
